include: "rules/common.smk"

##### Target rules #####
# a target rule to define the desired final output

rule all:
    input:
        "results/qc/multiqc.html",
        "results/annotated/funcotator/all.vcf.gz",
        "results/plots/depths.svg",
        "results/plots/allele-freqs.svg"


##### Modules #####

include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filtering.smk"
include: "rules/stats.smk"
include: "rules/qc.smk"
include: "rules/annotation.smk"

##### Addiional Modules #####
#include: "rules/eval.smk"
